// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model_test

import (
	"github.com/stephenafamo/bob"

	models "github.com/zunkk/go-project-startup/internal/core/model"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &models.User{}

// Make sure the type UserAuth runs hooks after queries
var _ bob.HookableType = &models.UserAuth{}
