// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"

	models "github.com/zunkk/go-project-startup/internal/core/model"
)

type contextKey string

var (
	// Table context

	userCtx     = newContextual[*models.User]("user")
	userAuthCtx = newContextual[*models.UserAuth]("userAuth")

	// Relationship Contexts for user
	userWithParentsCascadingCtx = newContextual[bool]("userWithParentsCascading")

	// Relationship Contexts for user_auth
	userAuthWithParentsCascadingCtx = newContextual[bool]("userAuthWithParentsCascading")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
